services:
  regressionecho:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      PW_HEADLESS: "true"
      CI: "1"
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./config:/app/config
      - ./storage:/app/storage
      - ./tests:/app/tests
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    tty: true
    stdin_open: true
